In [16]:
import pandas as pd

In [17]:
# 1. Load datasets
patients = pd.read_csv("Patient_Data.csv")
billing = pd.read_csv("Billing_Data.csv")

In [18]:
patients.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [19]:
billing.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [20]:
# Show summary
print("Patient Info:\n")
print(patients.info())

Patient Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 464.0+ bytes
None

In [21]:
# 2. Select relevant columns
patients = patients[['PatientID', 'Department', 'Doctor', 'BillAmount']]

In [22]:
patients.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

In [23]:
# 3. Drop unnecessary columns (safe)
patients = patients.drop(columns=['ReceptionistID', 'CheckInTime'], errors='ignore')

In [24]:
patients.head()

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN

In [25]:
# 4. Groupby - total bill per department
dept_bill = patients.groupby('Department')['BillAmount'].sum()
print("\nTotal Bill per Department:\n", dept_bill)

Total Bill per Department:
 Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [26]:
# 5. Remove duplicates
patients = patients.drop_duplicates(subset='PatientID')

In [29]:
# 6. Fill missing BillAmount with mean
patients['BillAmount'].fillna(patients['BillAmount'].mean(), inplace=True)

C:\Users\SHAIKH\AppData\Local\Temp\ipykernel_8480\4096754662.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  patients['BillAmount'].fillna(patients['BillAmount'].mean(), inplace=True)

In [30]:
# 7. Merge datasets
merged_df = pd.merge(patients, billing, on='PatientID', how='inner')

In [31]:
# 8. Add new patients (row-wise)
new_patients = pd.DataFrame({
    'PatientID': [999, 1000],
    'Department': ['Cardiology', 'Neurology'],
    'Doctor': ['Dr X', 'Dr Y'],
    'BillAmount': [8000, 9000]
})

In [32]:
final_df = pd.concat([merged_df, new_patients], axis=0, ignore_index=True)

In [33]:
# 9. Add new columns (column-wise)
final_df['InsuranceCovered'] = True
final_df['FinalAmount'] = final_df['BillAmount'] * 0.9

In [34]:
# Final Output
print("\nFinal Cleaned Dataset:\n")
print(final_df)

Final Cleaned Dataset:

   PatientID   Department     Doctor   BillAmount  InsuranceCovered  \
0        101   Cardiology  Dr. Smith  5000.000000              True
1        102    Neurology   Dr. John  6233.333333              True
2        103  Orthopedics    Dr. Lee  7500.000000              True
3        104   Cardiology  Dr. Smith  6200.000000              True
4        105  Dermatology   Dr. Rose  6233.333333              True
5        999   Cardiology       Dr X  8000.000000              True
6       1000    Neurology       Dr Y  9000.000000              True

   FinalAmount
0       4500.0
1       5610.0
2       6750.0
3       5580.0
4       5610.0
5       7200.0
6       8100.0

## conclusion
- The dataset was cleaned by removing duplicates and handling missing values.
- Data from multiple sources was merged using PatientID.
- Department-wise billing analysis was performed using groupby.
- Additional patient data and billing features were added for better analysis